language: node_js
node_js:
  - 12
  services:
  - postgresql
  before_script:
    npm install
  - psql -c 'create database  greetings-webapp;' -U postgres
  script:
- npm run test

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetings-webapp

